config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  post :paypal_webhooks, to: 'paypal_webhooks#create'
  namespace :admin do
    namespace :sellers do
      resources :prices, path: :offers
      resource :prices_import, only: [:create]
      resources :shipments, only: [:index, :edit, :update] do
        member do
          get :accept
          get :cancel
          get :reject
          get :ship
        end
        resources :line_items, only: [:update]
      end
      get :paypal_callbacks, to: 'paypal_callbacks#show'
      get :dashboard, to: 'dashboard#show'
    end

    resources :sellers do
      member do
        get :start_onboarding_process
      end
    end
  end
end

app/models/solidus_paypal_marketplace/sellers/captures/status_refresh.rb
# frozen_string_literal: true

module SolidusPaypalMarketplace
  module Sellers
    module Captures
      class StatusRefresh
        def self.call(*args)
          new.call(*args)
        end

        def call(capture_id)
          payment_source = SolidusPaypalCommercePlatform::PaymentSource.find_by!(capture_id: capture_id)
          capture_status = SolidusPaypalMarketplace::PaypalPartnerSdk.show_captured_payment_details(
            capture_id: capture_id
          )
          status = capture_status.status.downcase
          payment_source.update!(response_status: status)
          payment_source.payments.each do |payment|
            payment.started_processing!
            payment.complete! if status == 'completed' && payment.completed? != true
            payment.failure! if status == 'declined' && payment.failed? != true
          end
          true
        end
      end
    end
  end
end

app/models/solidus_paypal_marketplace/sellers/shipment_management/accept.rb
# frozen_string_literal: true

module SolidusPaypalMarketplace
  module Sellers
    module ShipmentManagement
      class Accept < Base
        def call(shipment)
          return false unless shipment.order.payments.all?(&:can_complete?)

          shipment.order.payments.each(&:capture!)
          true
        end
      end
    end
  end
end

app/models/solidus_paypal_marketplace/sellers/shipment_management/base.rb
# frozen_string_literal: true

module SolidusPaypalMarketplace
  module Sellers
    module ShipmentManagement
      class Base
        def self.call(*args)
          new.call(*args)
        end

        def call(*)
          raise NotImplementedError, 'Missing #call method on class'
        end
      end
    end
  end
end

app/models/solidus_paypal_marketplace/sellers/shipment_management/cancel.rb
# frozen_string_literal: true

module SolidusPaypalMarketplace
  module Sellers
    module ShipmentManagement
      class Cancel < Base
        def call(shipment)
          return false unless shipment.can_cancel?

          shipment.cancel!
        end
      end
    end
  end
end

app/models/solidus_paypal_marketplace/sellers/shipment_management/reject.rb
# frozen_string_literal: true

module SolidusPaypalMarketplace
  module Sellers
    module ShipmentManagement
      class Reject < Base
        def call(shipment, merchant_id_in_paypal: nil)
          payments = shipment.order.payments.map do |payment|
            payment.request_env = { merchant_id_in_paypal: merchant_id_in_paypal }
            payment
          end
          return false unless payments.all?(&:can_void?) && shipment.can_cancel?

          ActiveRecord::Base.transaction do
            payments.each(&:void_transaction!)
            shipment.cancel!
          end
        end
      end
    end
  end
end

app/models/solidus_paypal_marketplace/sellers/shipment_management/ship.rb
# frozen_string_literal: true

module SolidusPaypalMarketplace
  module Sellers
    module ShipmentManagement
      class Ship < Base
        def call(shipment)
          return false unless shipment.can_ship?

          shipment.ship!
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers/dashboard_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    module Sellers
      class DashboardController < Spree::Admin::BaseController
        skip_before_action :authorize_admin

        def show
          authorize! :visit, :seller_dashboard

          @seller = current_spree_user.seller
          refresh_seller_status if params[:refresh_seller_status]
          render locals: @locals || {}
        end

        private

        def refresh_seller_status
          seller_status = SolidusPaypalMarketplace::Sellers::StatusRefresh.call(
            @seller, return_url: admin_sellers_paypal_callbacks_url
          )
          restart_onboarding_process if seller_status.wrong_oauth_third_party_permissions
          @seller.reload
          @locals = {
            unconfirmed_primary_email: seller_status.unconfirmed_primary_email,
            wrong_oauth_third_party_permissions: seller_status.wrong_oauth_third_party_permissions
          }
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers/line_items_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    module Sellers
      class LineItemsController < Spree::Admin::Sellers::ResourceController
        def update
          @shipment = Spree::Shipment.find_by(number: params[:shipment_id])
          authorize! :manage, @shipment
          @line_item.update(quantity: permitted_resource_params[:quantity])
          redirect_to spree.edit_admin_sellers_shipment_path(@shipment)
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers/paypal_callbacks_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    module Sellers
      class PaypalCallbacksController < Spree::Admin::BaseController
        skip_before_action :authorize_admin

        def show
          authorize! :visit, :paypal_callbacks

          @seller = Spree::Seller.find_by!(merchant_id: params[:merchantId])
          redirect_params = {}

          if current_spree_user.seller == @seller
            if params[:permissionsGranted] == 'true'
              if @seller.pending?
                @seller.update(
                  merchant_id_in_paypal: params[:merchantIdInPayPal],
                  status: :waiting_paypal_confirmation
                )
                redirect_params = { refresh_seller_status: true }
                flash[:success] = I18n.t('spree.admin.paypal_callbacks.waiting_webhook_confirmation')
              else
                flash[:error] = I18n.t('spree.admin.paypal_callbacks.seller_already_processed')
              end
            else
              @seller.start_onboarding_process(return_url: admin_sellers_paypal_callbacks_url)
              flash[:error] = I18n.t('spree.admin.paypal_callbacks.granted_permissions_insufficient')
            end
          else
            flash[:error] = I18n.t('spree.admin.paypal_callbacks.sign_up_link_not_related')
          end

          redirect_to admin_sellers_dashboard_path(redirect_params)
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers/prices_controller.rb
# frozen_string_literal: true

require 'csv'

module Spree
  module Admin
    module Sellers
      class PricesController < Spree::Admin::Sellers::ResourceController
        include Spree::Core::ControllerHelpers::Pricing
        respond_to :html, :csv

        after_action :save_seller_stock_availability, if: -> { permitted_resource_params[:seller_stock_availability] },
                                                      only: [:create, :update]

        def index
          session[:return_to] = request.url
          @collection = @collection.currently_valid
                                   .where(currency: current_pricing_options.currency)
          respond_to do |format|
            format.html do
              @search = @collection.ransack(params[:q])
              @collection = @search.result.page(params[:page])
            end
            format.csv do
              @collection = @collection.group_by(&:variant_id).map { |_k, v| v.first }
            end
          end
        end

        private

        def flash_message_for(*args, **kwargs, &block)
          super(*args, **kwargs, &block).gsub(@object.class.model_name.human, t('spree.offer'))
        end

        def build_resource
          super.tap do |price|
            price.seller_id = spree_current_user.seller_id
          end
        end

        def save_seller_stock_availability
          @object.save_seller_stock_availability(originator: spree_current_user.seller)
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers/prices_imports_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    module Sellers
      class PricesImportsController < Spree::Admin::BaseController
        include Spree::Core::ControllerHelpers::Pricing

        def create
          csv_path = params["prices"].path
          importer = SolidusPaypalMarketplace::Importer::Price.new(
            currency: current_pricing_options.currency,
            file: csv_path,
            prices_scope: model_class.accessible_by(current_ability)
          )
          import = importer.import

          info = I18n.t('solidus_paypal_marketplace.offer_importer.result')

          if import.errors.any?
            flash[:notice] = info + I18n.t(
              'solidus_paypal_marketplace.offer_importer.result_with_error', errors: import.errors.join(', ')
            )
          else
            flash[:success] = info
          end

          redirect_to spree.admin_sellers_prices_path
        end

        private

        def model_class
          Spree::Price
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers/resource_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    module Sellers
      class ResourceController < Spree::Admin::ResourceController
        before_action :complete_paypal_onboarding, unless: -> { current_spree_user.seller.accepted? }

        private

        def complete_paypal_onboarding
          flash[:error] = I18n.t('spree.seller.paypal_account_not_connected')

          redirect_to admin_sellers_dashboard_path
        end

        def new_object_url(options = {})
          if parent?
            spree.new_polymorphic_url([:admin, :sellers, parent, model_class], options)
          else
            spree.new_polymorphic_url([:admin, :sellers, model_class], options)
          end
        end

        def edit_object_url(object, options = {})
          if parent?
            spree.polymorphic_url([:edit, :admin, :sellers, parent, object], options)
          else
            spree.polymorphic_url([:edit, :admin, :sellers, object], options)
          end
        end

        def object_url(object = nil, options = {})
          target = object || @object

          if parent?
            spree.polymorphic_url([:admin, :sellers, parent, target], options)
          else
            spree.polymorphic_url([:admin, :sellers, target], options)
          end
        end

        def collection_url(options = {})
          if parent?
            spree.polymorphic_url([:admin, :sellers, parent, model_class], options)
          else
            spree.polymorphic_url([:admin, :sellers, model_class], options)
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers/shipments_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    module Sellers
      class ShipmentsController < Spree::Admin::Sellers::ResourceController
        before_action :refresh_payments_statuses, only: [:edit],
                                                  if: -> { params[:refresh_payments_statuses] }

        def index
          session[:return_to] = request.url
          @collection = @collection.reverse_chronological
          @search = @collection.ransack(params[:q])
          @collection = @search.result.page(params[:page])
          respond_with(@collection)
        end

        def accept
          if SolidusPaypalMarketplace::Sellers::ShipmentManagement::Accept.call(@shipment)
            flash[:success] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.accept_successfully')
          else
            flash[:error] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.accept_failed')
          end
          redirect_to spree.edit_admin_sellers_shipment_url(@shipment)
        end

        def cancel
          if SolidusPaypalMarketplace::Sellers::ShipmentManagement::Cancel.call(@shipment)
            flash[:success] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.cancel_successfully')
          else
            flash[:error] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.cancel_failed')
          end
          redirect_to spree.edit_admin_sellers_shipment_url(@shipment)
        end

        def reject
          if SolidusPaypalMarketplace::Sellers::ShipmentManagement::Reject.call(
            @shipment, merchant_id_in_paypal: current_spree_user.seller.merchant_id_in_paypal
          )
            flash[:success] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.reject_successfully')
          else
            flash[:error] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.reject_failed')
          end
          redirect_to spree.edit_admin_sellers_shipment_url(@shipment)
        end

        def ship
          if SolidusPaypalMarketplace::Sellers::ShipmentManagement::Ship.call(@shipment)
            flash[:success] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.ship_successfully')
          else
            flash[:error] = I18n.t('solidus_paypal_marketplace.sellers.shipment_management.ship_failed')
          end
          redirect_to spree.edit_admin_sellers_shipment_url(@shipment)
        end

        private

        def find_resource
          Spree::Shipment.find_by(number: params[:id])
        end

        def location_after_save
          spree.edit_admin_sellers_shipment_url(@shipment)
        end

        def refresh_payments_statuses
          @shipment.order.payments.map(&:source).uniq.each do |source|
            next unless source.is_a?(SolidusPaypalCommercePlatform::PaymentSource)

            SolidusPaypalMarketplace::Sellers::Captures::StatusRefresh.call(source.capture_id)
          end
          @shipment.reload
        end
      end
    end
  end
end

app/controllers/spree/admin/sellers_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class SellersController < Spree::Admin::ResourceController
      after_action :_start_onboarding, if: -> { @seller.persisted? },
                                       only: :create
      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def start_onboarding_process
        result = _start_onboarding
        if result.present?
          flash[:success] = I18n.t('spree.seller.start_onboarding_successfully')
        else
          flash[:error] = I18n.t('spree.seller.start_onboarding_failed')
        end

        redirect_back fallback_location: edit_admin_seller_path(@seller)
      end

      private

      def collection
        return @collection if @collection.present?

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result.page(params[:page])
      end

      def _start_onboarding
        authorize! :start_onboarding, @seller

        @seller.start_onboarding_process(return_url: admin_sellers_paypal_callbacks_url)
      end
    end
  end
end

app/views/spree/admin/sellers/_form.html.erb
<div data-hook="admin_seller_form_fields">

  <div data-hook="admin_seller_form_name">
    <%= f.field_container :name do %>
      <%= f.label :name, class: 'required' %>
      <%= f.text_field :name, class: 'fullwidth title', required: true %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div data-hook="admin_seller_form_percentage">
    <%= f.field_container :percentage do %>
      <%= f.label :percentage, class: 'required' %>
      <%= f.text_field :percentage, class: 'fullwidth title', required: true %>
      <%= f.error_message_on :percentage %>
    <% end %>
  </div>

</div>

app/views/spree/admin/sellers/_user_form_fields.html.erb
<div data-hook="admin_seller_form_users_fields">
  <% user = @seller.users.first || @seller.users.new %>
  <% user.valid? %>

  <%= f.fields_for :users, user do |user_fields|%>

    <div data-hook="admin_seller_form_users_email">
      <%= f.field_container 'users.email' do %>
        <%= user_fields.label :email %>
        <%= user_fields.text_field :email, class: 'fullwidth title' %>
        <%= f.error_message_on 'users.email' %>
      <% end %>
    </div>

    <div data-hook="admin_seller_form_users_password">
      <%= f.field_container 'users.password' do %>
        <%= user_fields.label :password %>
        <%= user_fields.password_field :password, class: 'fullwidth title' %>
        <%= f.error_message_on 'users.password' %>
      <% end %>
    </div>

    <div data-hook="admin_seller_form_users_password">
      <%= f.field_container 'users.password_confirmation' do %>
        <%= user_fields.label :password_confirmation %>
        <%= user_fields.password_field :password_confirmation, class: 'fullwidth title' %>
        <%= f.error_message_on 'users.password_confirmation' %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/spree/admin/sellers/edit.html.erb
<% content_for :page_actions do %>
  <% if @seller.pending? && can?(:start_onboarding, Spree::Seller) %>
    <li id="start_onboarding_link">
      <%=
        link_to(
          @seller.action_url.present? ? t('spree.seller.refresh_sign_up_link') : t('spree.seller.start_onboarding'),
          start_onboarding_process_admin_seller_path(@seller),
          id: 'admin_seller_start_onboarding',
          class: 'btn btn-primary'
        )
      %>
    </li>
  <% end %>
<% end %>

<% admin_breadcrumb(link_to plural_resource_name(Spree::Seller), spree.admin_sellers_path) %>
<% admin_breadcrumb(@seller.name) %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @seller } %>

<%= form_for [:admin, @seller] do |f| %>
  <fieldset data-hook="new_seller">
    <legend align="center"><%= t('spree.edit_seller') %></legend>

    <%= render partial: 'form', locals: { f: f } %>

    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/sellers/index.html.erb
<% admin_breadcrumb(t('spree.offers')) %>

<% content_for :page_actions do %>
  <li>
    <%= link_to "#{t('spree.new_seller')}", new_admin_seller_url, class: 'btn btn-primary' %>
  </li>
<% end %>

<% content_for :table_filter_title do %>
  <%= t('spree.search') %>
<% end %>

<% if @collection.any? %>
  <table class="index" id="listing_sellers">
    <colgroup>
       <col style="width: 25%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 5%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_sellers_index_headers">
        <th>
          <%= sort_link @search,
                        :name,
                        Spree::Seller.human_attribute_name(:name),
                        { default_order: "desc" },
                        {title: 'admin_sellers_listing_name_title'} %></th>
        <th>
          <%= Spree::Variant.human_attribute_name(:percentage) %>
        </th>
        <th>
          <%= Spree::Variant.human_attribute_name(:status) %>
        </th>
        <th colspan="2">
          <%= Spree::Variant.human_attribute_name(:risk_status) %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |seller| %>
          <tr id="<%= spree_dom_id seller %>" data-hook="admin_sellers_index_rows">
            <td><%= seller.name %></td>
            <td><%= seller.percentage %></td>
            <td><%= seller.status %></td>
            <td><%= seller.risk_status %></td>
            <td class="actions" data-hook="admin_sellers_index_row_actions">
              <%= link_to_edit seller, no_text: true, class: 'edit' if can?(:edit, seller) %>
              &nbsp;
              <%= link_to_delete seller, no_text: true if can?(:destroy, seller) %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                  resource: Spree::Seller,
                  new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/sellers/new.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Seller), spree.admin_sellers_path) %>
<% admin_breadcrumb(t('spree.new_seller')) %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @seller } %>

<%= form_for [:admin, @seller] do |f| %>
  <fieldset data-hook="new_seller">
    <legend align="center"><%= t('spree.new_seller') %></legend>

    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'user_form_fields', locals: { f: f } %>

    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>